Repository DIT113-V22/group-10, pull requests merged in 2022-05, with the labels that each got.

#42 Add joystick controls for car
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/example/hermes/AbstractSteering.java
  Android/app/src/main/java/com/example/hermes/CarControl.java
  Android/app/src/main/java/com/example/hermes/ControlSelection.java
  Android/app/src/main/java/com/example/hermes/First2Fragment.java
  Android/app/src/main/java/com/example/hermes/Joystick.java
  Android/app/src/main/java/com/example/hermes/JsonManager.java
  Android/app/src/main/java/com/example/hermes/MainActivity.java
  Android/app/src/main/java/com/example/hermes/Second2Fragment.java
  Android/app/src/main/res/layout/activity_car_control.xml
  Android/app/src/main/res/layout/activity_control_selection.xml
  Android/app/src/main/res/layout/activity_joystick.xml
  Android/app/src/main/res/layout/content_joystick.xml
  Android/app/src/main/res/layout/fragment_first2.xml
  Android/app/src/main/res/layout/fragment_second2.xml
  Android/app/src/main/res/navigation/nav_graph2.xml
  Android/app/src/main/res/navigation/nav_graph3.xml
  Android/app/src/main/res/values/refs.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/test/java/com/example/hermes/ExampleUnitTest.java
  Android/joystickView/.gitignore
  Android/joystickView/build.gradle
  Android/joystickView/proguard-rules.pro
  Android/joystickView/src/androidTest/java/com/zerokol/views/joystickView/ExampleInstrumentedTest.java
  Android/joystickView/src/main/AndroidManifest.xml
  Android/joystickView/src/main/java/com/zerokol/views/joystickView/JoystickView.java
  Android/joystickView/src/test/java/com/zerokol/views/joystickView/ExampleUnitTest.java
  Android/local.properties
  Android/settings.gradle
  arduino/arduinoD/arduinoD.ino
Labels: Sprint#2

#47 Obstacle warning/avoidance
  .github/workflows/arduino-build.yml
  Android/app/src/main/java/com/example/hermes/AbstractSteering.java
  Android/app/src/main/java/com/example/hermes/CarControl.java
  arduino/arduinoD/arduinoD.ino
  arduino/smartcar/smartcar.ino
Labels: Sprint#2

#51 Obstacle message
  Android/app/src/main/java/com/example/hermes/AbstractSteering.java
  Android/app/src/main/java/com/example/hermes/CarControl.java
  Android/app/src/main/java/com/example/hermes/DatabaseManager.java
  Android/app/src/main/java/com/example/hermes/Joystick.java
  Android/app/src/main/res/layout/activity_car_control.xml
  Android/app/src/main/res/layout/activity_joystick.xml
Labels: Sprint#3

#61 Sorting
  Android/app/src/main/java/com/example/hermes/Delivery.java
  Android/app/src/main/java/com/example/hermes/JsonManager.java
  Android/app/src/main/java/com/example/hermes/SectionsPageAdapter.java
  Android/app/src/main/java/com/example/hermes/data/test.Json
  Android/app/src/main/java/com/example/hermes/deliveryTabs.java
  Android/app/src/main/java/com/example/hermes/tab1Fragment.java
  Android/app/src/main/java/com/example/hermes/tab2Fragment.java
  Android/app/src/main/java/com/example/hermes/ui/CustomListAdapter.java
  Android/app/src/main/res/layout/all_deliveries.xml
  Android/app/src/main/res/layout/tab1fragment.xml
  Android/app/src/main/res/layout/tab2fragment.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/test/java/com/example/hermes/ExampleUnitTest.java
Labels: enhancement
